name: "Create built versions cache"

on:
  push:
  workflow_dispatch:

jobs:
  eval_cache:
    runs-on: ubuntu-latest
    concurrency: ${{ github.ref}}
    steps:
      - uses: actions/checkout@v2.4.0

      - name: Cache multiple paths
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/nix
          key: ${{ runner.os }}-${{ github.run_id}}
          restore-keys: |
            ${{ runner.os }}-

      - uses: flox/flox-integration-action@master
        with:
          substituter: https://storehouse.beta.floxdev.com/project/flox-examples
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          git_token: ${{ secrets.GIT_TOKEN }}
          attr_path: packages.x86_64-linux.hello-go
